config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="homepage.html"), name='home'),
    path('', include('django_shop.account.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_shop/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import (
    Register,
    Login,
    logout_view,
    ProfilePersonalInfo
)

app_name = 'account'
urlpatterns = [
    path('sign-up', Register.as_view(), name='sign-up'),
    path('login', Login.as_view(), name='login'),
    path('logout', logout_view, name='logout'),
    path('profile', ProfilePersonalInfo.as_view(), name='profile'),
    
    path('password_reset/', auth_views.PasswordResetView.as_view(
        success_url=reverse_lazy('account:password_reset_done')), name='password_reset'),
    
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('account:password_reset_complete')), name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password_change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy('account:password_change_done')), name='password_change'),

    path('password_change/done', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
]

django_shop/account/models.py
import re

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import BaseUserManager
from django.core.exceptions import ValidationError


class UserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)



def validate_phone(value):
    if not bool(re.match('(09\d{9})', value)) or len(value) != 11:
        raise ValidationError('شماره موبایل وارد شده غیر مجاز است.')
    return value


class User(AbstractUser):
    """
    Custom User model. Email & Phone as identifier
    """
    username = None
    email = models.EmailField('ایمیل', max_length=254, unique=True)
    phone = models.CharField('شماره موبایل', max_length=11, unique=True, validators=[validate_phone])
    avatar = models.ImageField('تصویر پروفایل', upload_to='avatar', blank=True, default="defaultavatar.png")

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['phone']

django_shop/products/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

class Product(models.Model):
    """
    Abstract product model contains common fields among all products
    TODO:
        - cateogries
        - gallery
    """
    title = models.CharField('عنوان محصول', max_length=50)
    description = models.TextField('توضیحات')
    cover = models.ImageField('کاور محصول', upload_to=None)
    price = models.PositiveIntegerField('قیمت')
    discount_percent = models.PositiveSmallIntegerField('درصد تخفیف', blank=True, default=0)
    available_count = models.PositiveSmallIntegerField('موجودی انبار')
    technical_details = models.JSONField('مشخصات فنی')
    attributes = ArrayField(
        'امکانات محصول',
        models.CharField(max_length=100, blank=True),
        blank = True, null = True)
    is_active = models.BooleanField('فعال/غیرفعال', default=False)


    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    @property
    def final_price(self):
        """Calculate the final price of product with discount"""
        final_price = self.price * (100 - self.discount) / 100
        return final_price

    @property
    def is_available(self):
        """Returns True if the product is available"""
        if self.availlable_count > 0:
            return True
        return False

django_shop/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "phone", "password1", "password2")

class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email", "phone", "first_name", "last_name", "avatar")
        
        widgets = {
            'avatar': forms.FileInput()
        }

django_shop/account/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
	DetailView,
	CreateView,
	UpdateView )
from django.contrib import messages

from .models import User
from .forms import SignupForm, PersonalInfoForm


class Register(CreateView):
	"""
	User registration view
	"""
	form_class = SignupForm
	template_name = "registration/signup.html"
	success_url = reverse_lazy('account:login')

	def get(self, request):
		"""Redirects user to homepage if is authenticated"""
		if request.user.is_authenticated:
			return redirect('/')
		return super().get(request)

	def form_valid(self, form):
		"""Create a new user"""
		user = form.save(commit=False)
		user.set_password(form.cleaned_data['password1'])
		user.save()
		return super().form_valid(form)


class Login(LoginView):
	"""
	User login view with email/phone
	"""
	template_name = "registration/login.html"

	def get_success_url(self):
		return reverse_lazy('home')

	def form_invalid(self, form):
		"""Returns a message if credentials are invalid"""
		messages.add_message(self.request, messages.ERROR, 'کاربری با مشخصات وارد شده یافت نشد!')
		return super().form_invalid(form)


@login_required
def logout_view(request):
    logout(request)
    return redirect('/login')


class ProfilePersonalInfo(LoginRequiredMixin, UpdateView, DetailView):
	"""
	User's profile page. Edit personal info
	"""
	model = User
	form_class = PersonalInfoForm
	template_name = "registration/profile_personal_info.html"
	success_url = reverse_lazy("account:profile")

	def get_object(self):
		return self.request.user

django_shop/products/views.py
from django.shortcuts import render

# Create your views here.

django_shop/templates/partials/_FooterReferences.html
{% load static %}

<script src="{% static 'js/vendor/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/vendor/popper.min.js' %}"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/vendor/imagesloaded.min.js' %}"></script>
<script src="{% static 'js/vendor/isotope.min.js' %}"></script>
<script src="{% static 'js/vendor/iziToast.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery.countdown.min.js' %}"></script>
<script src="{% static 'js/vendor/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/vendor/nouislider.min.js' %}"></script>
<script src="{% static 'js/vendor/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/theme.js' %}"></script>

django_shop/templates/partials/_HeaderReferences.html
{% load static %}

<!-- Vendor Styles including: Font Icons, Plugins, etc.-->
<link rel="stylesheet" href="{% static 'css/vendor/feather.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/iziToast.min.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/fancybox.min.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/noUISlider.min.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/owl.carousel.min.css' %}">
<link rel="stylesheet" href="{% static 'css/vendor/socicon.css' %}">
<!-- Main Theme Styles + Bootstrap-->
<link rel="stylesheet" media="screen" href="{% static 'css/theme.css' %}">
<!-- Modernizr-->
<script src="{% static 'js/modernizr.min.js' %}"></script>

django_shop/templates/partials/footer.html
{% load static %}
<!-- Footer-->
<footer class="bg-dark pt-5">
    <!-- First Row-->
    <div class="container pt-2">
      <div class="row">
        <!-- Shop Departments-->
        <div class="col-lg-6">
          <div class="widget widget-light-skin mb-0">
            <h4 class="widget-title">فروشگاه ها</h4>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="widget widget-categories widget-light-skin">
                <ul>
                  <li><a href="#">کامپیوترها و لوازم جانبی</a></li>
                  <li><a href="#">گوشی های هوشمند و تبلت</a></li>
                  <li><a href="#">تلویزیون، ویدئو و صوتی</a></li>
                  <li><a href="#">دوربین ها، عکس و ویدئو</a></li>
                  <li><a href="#">هدفون</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="widget widget-categories widget-light-skin">
                <ul>
                  <li><a href="#">چاپگر ها</a></li>
                  <li><a href="#">بازی های ویدئویی</a></li>
                  <li><a href="#">لوازم الکترونیکی</a></li>
                  <li><a href="#">ابزارهای موسیقی</a></li>
                  <li><a href="#">نرم‌افزار</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- About Links-->
        <div class="col-lg-3 col-sm-6">
          <div class="widget widget-categories widget-light-skin">
            <h4 class="widget-title">درباره ما</h4>
            <ul>
              <li><a href="#">شغل</a></li>
              <li><a href="#">درباره CreateX</a></li>
              <li><a href="#">داستان ما</a></li>
              <li><a href="#">خدمات ما</a></li>
              <li><a href="#">وبلاگ ما</a></li>
              <li><a href="#">تماس با ما</a></li>
            </ul>
          </div>
        </div>
        <!-- Account Links-->
        <div class="col-lg-3 col-sm-6">
          <div class="widget widget-categories widget-light-skin">
            <h4 class="widget-title">حساب و اطلاعات حمل و نقل</h4>
            <ul>
              <li><a href="#">حساب من</a></li>
              <li><a href="#">هزینه حمل و نقل و سیاست</a></li>
              <li><a href="#">بازپرداخت و جایگزینی</a></li>
              <li><a href="#">مالیات</a></li>
              <li><a href="#">اطلاعات تحویل</a></li>
              <li><a href="#">برنامه های وابسته</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- Second Row-->
    <div class="pt-5" style="background-color: #30363d;">
      <div class="container">
        <div class="row">
          <!-- Contacts-->
          <div class="col-lg-3 col-sm-6">
            <div class="widget widget-contacts widget-light-skin mb-4">
              <h4 class="widget-title">با ما در تماس باشید</h4>
              <ul>
                <li><i class="fe-icon-map-pin"></i><span>ما رو پیدا کن</span><a href="#">ایران - تهران</a></li>
                <li><i class="fe-icon-phone"></i><span>با ما تماس بگیرید</span><a href="tel:02111111111">۰۲۱-۱۱۱۱۱۱۱۱</a></li>
                <li><i class="fe-icon-mail"></i><span>ایمیل</span><a href="mailto:info@example.com">info@example.com</a></li>
              </ul>
            </div>
            <div class="widget pt-2"><a class="social-btn sb-style-6 sb-facebook sb-light-skin" href="#"><i class="socicon-facebook"></i></a><a class="social-btn sb-style-6 sb-twitter sb-light-skin" href="#"><i class="socicon-twitter"></i></a><a class="social-btn sb-style-6 sb-youtube sb-light-skin" href="#"><i class="socicon-youtube"></i></a><a class="social-btn sb-style-6 sb-instagram sb-light-skin" href="#"><i class="socicon-instagram"></i></a><a class="social-btn sb-style-6 sb-pinterest sb-light-skin" href="#"><i class="socicon-pinterest"></i></a></div>
          </div>
          <!-- Mobile App-->
          <div class="col-lg-3 col-sm-6">
            <div class="widget widget-light-skin">
              <h4 class="widget-title">برنامه موبایل ما</h4><a class="market-btn apple-btn market-btn-light-skin ml-3 mb-3" href="#"><span class="mb-subtitle">Download on the</span><span class="mb-title">App Store</span></a><a class="market-btn google-btn market-btn-light-skin ml-3 mb-3" href="#"><span class="mb-subtitle">Download on the</span><span class="mb-title">Google Play</span></a><a class="market-btn windows-btn market-btn-light-skin ml-3 mb-3" href="#"><span class="mb-subtitle">Download on the</span><span class="mb-title">Windows Store</span></a><a class="market-btn amazon-btn market-btn-light-skin ml-3 mb-3" href="#"><span class="mb-subtitle">Order now at</span><span class="mb-title">Amazon.com</span></a>
            </div>
          </div>
          <!-- Subscription-->
          <div class="col-lg-6">
            <div class="widget widget-light-skin">
              <h4 class="widget-title">خبرنامه</h4>
              <form action="" method="post" target="_blank" novalidate>
                <div class="input-group">
                  <input class="form-control form-control-light-skin text-left placeholder-right" type="email" name="EMAIL" placeholder="آدرس ایمیل">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="submit">ثبت نام</button>
                  </div>
                </div><small class="form-text text-white opacity-50 pt-1">برای دریافت آخرین بروز رسانی ها و محصولات جدید ایمیل خود را وارد نمایید.</small>
              </form>
              <div class="pt-4 mt-2"><img class="d-block" src="{% static 'img/credit-cards-footer.png' %}" style="width: 324px;" alt="Credit Cards"></div>
            </div>
          </div>
        </div>
        <hr class="hr-light">
        <div class="d-md-flex justify-content-between align-items-center py-4 text-center text-md-left">
          <div class="order-2"><a class="footer-link text-white" href="#">درباره ما</a><a class="footer-link text-white mr-3" href="#">کمک و اطلاعات</a><a class="footer-link text-white mr-3" href="#">حریم خصوصی</a></div>
          <p class="m-0 text-sm text-white order-1"><span class='opacity-60'>همه حقوق محفوظ است.© ساخته شده با</span> <i class='d-inline-block align-middle fe-icon-heart text-danger'></i> <a href='https://www.rtl-theme.com/' class='d-inline-block nav-link text-white opacity-60 p-0' target='_blank'>راستچین</a></p>
        </div>
      </div>
    </div>
  </footer>

django_shop/templates/partials/header.html
{% load static %}




<div class="offcanvas-container is-triggered offcanvas-container-reverse" id="mobile-menu"><span class="offcanvas-close"><i class="fe-icon-x"></i></span>
        <div class="px-4 pb-4">
          <h6>منو</h6>
          <div class="d-flex justify-content-between pt-2">
            <a class="btn btn-primary btn-md center-block w-100" href="{% url 'account:sign-up' %}"><i class="fe-icon-user"></i>&nbsp;ثبت‌نام</a>
            <a class="btn btn-primary btn-md center-block w-100" href="{% url 'account:login' %}"><i class="fe-icon-user"></i>&nbsp;ورود</a>
            
          </div>
        </div>
        <div class="offcanvas-scrollable-area border-top" style="height:calc(100% - 235px); top: 144px;">
          <!-- Mobile Menu-->
          <div class="accordion mobile-menu" id="accordion-menu">
            <!-- Home-->
            <div class="card">
              <div class="card-header"><a class="mobile-menu-link" href="shop-boxed-ls.html">فروشگاه</a><a class="collapsed" href="#shop-submenu" data-toggle="collapse"></a></div>
              <div class="collapse" id="shop-submenu" data-parent="#accordion-menu">
                <div class="card-body">
                  <ul>
                    <li class="dropdown-header">طرح های فروشگاه</li>
                    <li class="dropdown-item"><a href="shop-boxed-ls.html">جعبه ای با ستون سمت چپ</a></li>
                    <li class="dropdown-item"><a href="shop-boxed-rs.html">جعبه ای با ستون سمت راست</a></li>
                    <li class="dropdown-item"><a href="shop-boxed-ft.html">جعبه ای با فیلتر محصولات</a></li>
                    <li class="dropdown-item"><a href="shop-boxed-ns.html">جعبه ای بدون سایدبار</a></li>
                    <li class="dropdown-item"><a href="shop-fw-ls.html">تمام صفحه با ستون چپ</a></li>
                    <li class="dropdown-item"><a href="shop-fw-rs.html">تمام صفحه با ستون راست</a></li>
                    <li class="dropdown-item"><a href="shop-fw-ft.html">تمام صفحه با فیلتر محصولات</a></li>
                    <li class="dropdown-item"><a href="shop-fw-ns.html">تمام صفحه بدون سایدبار</a></li>
                    <li class="dropdown-header">صفحات فروشگاه</li>
                    <li class="dropdown-item"><a href="shop-categories.html">دسته بندی محصولات</a></li>
                    <li class="dropdown-item"><a href="shop-single.html">">صفحه محصول</a></li>
                    <li class="dropdown-item"><a href="cart.html">سبد خرید</a></li>
                    <li class="dropdown-item"><a href="checkout-address.html">پرداخت - آدرس</a></li>
                    <li class="dropdown-item"><a href="checkout-shipping.html">پرداخت - حمل و نقل</a></li>
                    <li class="dropdown-item"><a href="checkout-payment.html">پرداخت</a></li>
                    <li class="dropdown-item"><a href="checkout-review.html">پرداخت - مرور</a></li>
                    <li class="dropdown-item"><a href="checkout-complete.html">پرداخت - تکمیل</a></li>
                  </ul>
                </div>
              </div>
            </div>
            <!-- Components-->
            <div class="card">
              <div class="card-header"><a class="mobile-menu-link" href="components.html">عناصر صفحه</a></div>
            </div>
          </div>
        </div>
        <div class="offcanvas-footer px-4 pt-3 pb-2 text-center"><a class="social-btn sb-style-3 sb-twitter" href="#"><i class="socicon-twitter"></i></a><a class="social-btn sb-style-3 sb-facebook" href="#"><i class="socicon-facebook"></i></a><a class="social-btn sb-style-3 sb-pinterest" href="#"><i class="socicon-pinterest"></i></a><a class="social-btn sb-style-3 sb-instagram" href="#"><i class="socicon-instagram"></i></a></div>
      </div>




<!-- Remove "navbar-sticky" class to make navigation bar scrollable with the page.-->
<header class="navbar-wrapper navbar-sticky">
    <div class="d-table-cell align-middle pl-md-3"><a class="navbar-brand ml-1" href="{% url 'home' %}"><img src="{% static 'img/logo/logo-dark.png' %}" alt="CreateX"/></a></div>
    <div class="d-table-cell w-100 align-middle pl-md-3">
        <div class="navbar-top d-none d-lg-flex justify-content-between align-items-center">
        <div><a class="navbar-link ml-3" href="tel:+02111111111"><i class="fe-icon-phone"></i>۰۲۱-۱۱۱۱۱۱۱۱</a><a class="navbar-link ml-3" href="mailto:support@example.com"><i class="fe-icon-mail"></i>support@example.com</a><a class="social-btn sb-style-3 sb-twitter" href="#"><i class="socicon-twitter"></i></a><a class="social-btn sb-style-3 sb-facebook" href="#"><i class="socicon-facebook"></i></a><a class="social-btn sb-style-3 sb-pinterest" href="#"><i class="socicon-pinterest"></i></a><a class="social-btn sb-style-3 sb-instagram" href="#"><i class="socicon-instagram"></i></a></div>
        <div>
            <ul class="list-inline mb-0">
            {% if request.user.is_authenticated %}
              <li class="dropdown-toggle mr-2"><a class="navbar-link" ><i class="fe-icon-user"></i>حساب کاربری</a>
                  <div class="dropdown-menu left-aligned p-3 text-center" style="min-width: 200px;">
                    <a class="btn btn-primary btn-sm btn-block" href="{% url 'account:profile' %}">ورود به حساب کاربری</a>
                    <a class="btn btn-primary btn-sm btn-block" href="{% url 'account:logout' %}">خروج از حساب کاربری</a>
                  </div>
              </li>
            {% else %}
              <li class="dropdown-toggle mr-2"><a class="navbar-link" ><i class="fe-icon-user"></i></a>
                <div class="dropdown-menu left-aligned p-3 text-center" style="min-width: 200px;">
                  <p class="text-sm opacity-70">به حساب خود وارد شوید یا ثبت نام کنید تا بتوانید کنترل کامل سفارشات خود را دریافت کنید، پاداش ها و موارد دیگر را دریافت کنید.</p><a class="btn btn-primary btn-sm btn-block" href="{% url 'account:login' %}">ورود</a>
                  <p class="text-sm text-muted mt-3 mb-0">مشتری جدید؟<a href="{% url 'account:sign-up' %}"> ثبت نام </a></p>
                </div>
            </li>
            {% endif %}
            </ul>
        </div>
        </div>
        <div class="navbar justify-content-end justify-content-lg-between">
        <!-- Search-->
        <form class="search-box" method="get">
            <input type="text" id="site-search" placeholder="جستجو کنید.دنبال چی هستید؟"><span class="search-close"><i class="fe-icon-x"></i></span>
        </form>




        <!-- Main Menu-->
        <ul class="navbar-nav d-none d-lg-block">
            <li class="nav-item mega-dropdown-toggle"><a class="nav-link" href="shop-boxed-ls.html">فروشگاه</a>
                <div class="dropdown-menu mega-dropdown">
                  <div class="d-flex">
                    <div class="column">
                      <div class="widget widget-custom-menu">
                        <a href="" style="text-decoration:none;"><h4 class="widget-title">طرح های فروشگاه</h4></a>
                        <ul>
                          <li><a href="shop-boxed-ls.html">جعبه ای با ستون سمت چپ</a></li>
                          <li><a href="shop-boxed-rs.html">جعبه ای با ستون سمت راست</a></li>
                          <li><a href="shop-boxed-ft.html">جعبه ای با فیلتر محصولات</a></li>
                          <li><a href="shop-boxed-ns.html">جعبه ای بدون سایدبار</a></li>
                          <li><a href="shop-fw-ls.html">تمام صفحه با ستون چپ</a></li>
                          <li><a href="shop-fw-rs.html">تمام صفحه با ستون راست</a></li>
                          <li><a href="shop-fw-ft.html">تمام صفحه با فیلتر محصولات</a></li>
                          <li><a href="shop-fw-ns.html">تمام صفحه بدون سایدبار</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="column">
                      <div class="widget widget-custom-menu">
                        <h4 class="widget-title">صفحات فروشگاه</h4>
                        <ul>
                          <li><a href="shop-categories.html">دسته بندی محصولات</a></li>
                          <li><a href="shop-single.html">صفحه محصول</a></li>
                          <li><a href="cart.html">سبد خرید</a></li>
                          <li><a href="checkout-address.html">پرداخت - آدرس</a></li>
                          <li><a href="checkout-shipping.html">پرداخت - حمل و نقل</a></li>
                          <li><a href="checkout-payment.html">پرداخت</a></li>
                          <li><a href="checkout-review.html">پرداخت - مرور</a></li>
                          <li><a href="checkout-complete.html">پرداخت - تکمیل</a></li>
                        </ul>
                      </div>
                    </div>
                    <div class="column p-0 ml-0 mr-3" style="width: 320px;"><a class="d-block" href="shop-single.html"><img src="{% static 'img/shop/mega-menu.jpg' %}" alt="Samsung Galaxy S9"/></a></div>
                  </div>
                </div>
              </li>
            <li class="nav-item"><a class="nav-link" href="components.html">عناصر صفحه</a></li>
        </ul>
        <div>
            <ul class="navbar-buttons d-inline-block align-middle mr-lg-2">
            <li class="d-block d-lg-none"><a href="#mobile-menu" data-toggle="offcanvas"><i class="fe-icon-menu"></i></a></li>
            <li><a href="#" data-toggle="search"><i class="fe-icon-search"></i></a></li>
            <li><a href="#shopping-cart" data-toggle="offcanvas"><i class="fe-icon-shopping-cart"></i></a><span class="badge badge-danger">3</span></li>
            </ul><a class="btn btn-gradient mr-3 d-none d-xl-inline-block" href="#" target="_blank">هم اکنون بخرید</a>
        </div>
        </div>
    </div>
          <!-- Off-Canvas Shopping Cart-->
      <div class="offcanvas-container is-triggered offcanvas-container-reverse" id="shopping-cart"><span class="offcanvas-close"><i class="fe-icon-x"></i></span>
        <div class="px-4">
          <h6>سبد خرید شما</h6>
          <div class="widget widget-cart pt-2"><a class="featured-product" href="shop-single.html">
              <div class="featured-product-thumb"><img src="{% static 'img/widgets/cart/02.jpg' %}" alt="Product Image"/>
              </div>
              <div class="featured-product-info">
                <h5 class="featured-product-title">Samsung Gear 360 Camera</h5><span class="featured-product-price">۴۵۳۰۰۰۰ تومان</span>
              </div><span class="remove-product"><i class="fe-icon-x"></i></span></a><a class="featured-product" href="shop-single.html">
              <div class="featured-product-thumb"><img src="{% static 'img/widgets/cart/03.jpg' %}" alt="Product Image"/>
              </div>
              <div class="featured-product-info">
                <h5 class="featured-product-title">Edifier W855BT Bluetooth</h5><span class="featured-product-price">۴۵۳۰۰۰۰ تومان</span>
              </div><span class="remove-product"><i class="fe-icon-x"></i></span></a>
            <hr class="mt-3 mb-3"><span class="text-sm text-muted">قیمت کل: &nbsp;</span><strong>۱۳۵۹۰۰۰۰ تومان</strong>
            <div class="d-flex justify-content-between pt-3"><a class="btn btn-primary btn-block btn-sm ml-2" href="cart.html">مشاهده سبد خرید</a><a class="btn btn-accent btn-block mt-0 btn-sm" href="checkout-address.html">پرداخت</a></div>
          </div>
        </div>
      </div>
</header>